#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script para corrigir o HTML quebrado
"""

import re


def corrigir_html():
    """Corrige o HTML que foi quebrado."""

    # Lê o arquivo
    with open("mostro _unificado_copia_do_v2.py", 'r', encoding='utf-8') as f:
        codigo = f.read()

    # Corrige tags HTML quebradas
    html_fixes = [
        ('< !DOCTYPE html >', '<!DOCTYPE html>'),
        ('< html >', '<html>'),
        ('< /html >', '</html>'),
        ('< head >', '<head>'),
        ('< /head >', '</head>'),
        ('< title >', '<title>'),
        ('< /title >', '</title>'),
        ('< body >', '<body>'),
        ('< /body >', '</body>'),
tyle > ', ' < style >'),
        ('< /style >', '</style>'),
        ('< script', '<script'),
        ('< /script >', '</script>'),
        ('< div', '<div'),
        ('< /div >', '</div>'),
        ('< h1 >', '<h1>'),
        ('< /h1 >', '</h1>'),
        ('< h2 >', '<h2>'),
        ('< /h2 >', '</h2>'),
        ('< h3 >', '<h3>'),
        ('< /h3 >', '</h3>'),
        ('< p >', '<p>'),
        ('< /p >', '</p>'),
        ('< br >', '<br>'),
        ('< hr >', '<hr>'),
        ('< span', '<span'),
        ('< /span >', '</span>'),
        ('< button', '<button'),
        ('< /button >', '</button>'),
        ('< input', '<input'),
        ('< select', '<select'),
        ('< /select >', '</select>'),
        ('< option', '<option'),
        ('< /option >', '</option>'),
        ('< table', '<table'),
        ('< /table >', '</table>'),
        ('< tr', '<tr'),
        ('< /tr >', '</tr>'),
        ('< td', '<td'),
        ('< /td >', '</td>'),
        ('< th', '<th'),
        ('< /th >', '</th>'),
        ('< ul', '<ul'),
        ('< /ul >', '</ul>'),
        ('< li', '<li'),
        ('< /li >', '</li>'),
        ('< a', '<a'),
        ('< /a >', '</a>'),
        ('< img', '<img'),
        ('< form', '<form'),
        ('< /form >', '</form>'),
        ('< label', '<label'),
        ('< /label >', '</label>'),
        ('< textarea', '<textarea'),
        ('< /textarea >', '</textarea>'),
        ('< canvas', '<canvas'),
        ('< /canvas >', '</canvas>'),
        ('< svg', '<svg'),
        ('< /svg >', '</svg>'),
        ('< path', '<path'),
        ('< /path >', '</path>'),
        ('< g', '<g'),
        ('< /g >', '</g>'),
        ('< rect', '<rect'),
        ('< /rect >', '</rect>'),
        ('< circle', '<circle'),
        ('< /circle >', '</circle>'),
        ('< line', '<line'),
        ('< /line >', '</line>'),
        ('< text', '<text'),
        ('< /text >', '</text>'),
        ('< defs', '<defs'),
        ('< /defs >', '</defs>'),
        ('< use', '<use'),
        ('< /use >', '</use>'),
        ('< symbol', '<symbol'),
        ('< /symbol >', '</symbol>'),
        ('< marker', '<marker'),
        ('< /marker >', '</marker>'),
        ('< pattern', '<pattern'),
        ('< /pattern >', '</pattern>'),
        ('< clipPath', '<clipPath'),
        ('< /clipPath >', '</clipPath>'),
        ('< mask', '<mask'),
        ('< /mask >', '</mask>'),
        ('< filter', '<filter'),
        ('< /filter >', '</filter>'),
        ('< feGaussianBlur', '<feGaussianBlur'),
        ('< /feGaussianBlur >', '</feGaussianBlur>'),
        ('< feOffset', '<feOffset'),
        ('< /feOffset >', '</feOffset>'),
        ('< feFlood', '<feFlood'),
        ('< /feFlood >', '</feFlood>'),
        ('< feComposite', '<feComposite'),
        ('< /feComposite >', '</feComposite>'),
        ('< feMerge', '<feMerge'),
        ('< /feMerge >', '</feMerge>'),
        ('< feMergeNode', '<feMergeNode'),
        ('< /feMergeNode >', '</feMergeNode>'),
        ('< animate', '<animate'),
        ('< /animate >', '</animate>'),
        ('< animateTransform', '<animateTransform'),
        ('< /animateTransform >', '</animateTransform>'),
        ('< animateMotion', '<animateMotion'),
        ('< /animateMotion >', '</animateMotion>'),
        ('< set', '<set'),
        ('< /set >', '</set>'),
        ('< mpath', '<mpath'),
        ('< /mpath >', '</mpath>'),
        ('< foreignObject', '<foreignObject'),
        ('< /foreignObject >', '</foreignObject>'),
        ('< switch', '<switch'),
        ('< /switch >', '</switch>'),
        ('< metadata', '<metadata'),
        ('< /metadata >', '</metadata>'),
        ('< desc', '<desc'),
        ('< /desc >', '</desc>'),
        ('< title', '<title'),
        ('< /title >', '</title>'),
        ('< style', '<style'),
        ('< /style >', '</style>'),
        ('< script', '<script'),
        ('< /script >', '</script>'),
        ('< noscript', '<noscript'),
        ('< /noscript >', '</noscript>'),
        ('< iframe', '<iframe'),
        ('< /iframe >', '</iframe>'),
        ('< embed', '<embed'),
        ('< /embed >', '</embed>'),
        ('< object', '<object'),
        ('< /object >', '</object>'),
        ('< param', '<param'),
        ('< /param >', '</param>'),
        ('< video', '<video'),
        ('< /video >', '</video>'),
        ('< audio', '<audio'),
        ('< /audio >', '</audio>'),
        ('< source', '<source'),
        ('< /source >', '</source>'),
        ('< track', '<track'),
        ('< /track >', '</track>'),
        ('< map', '<map'),
        ('< /map >', '</map>'),
        ('< area', '<area'),
        ('< /area >', '</area>'),
        ('< nav', '<nav'),
        ('< /nav >', '</nav>'),
        ('< header', '<header'),
        ('< /header >', '</header>'),
        ('< footer', '<footer'),
        ('< /footer >', '</footer>'),
        ('< section', '<section'),
        ('< /section >', '</section>'),
        ('< article', '<article'),
        ('< /article >', '</article>'),
        ('< aside', '<aside'),
        ('< /aside >', '</aside>'),
        ('< main', '<main'),
        ('< /main >', '</main>'),
        ('< details', '<details'),
        ('< /details >', '</details>'),
        ('< summary', '<summary'),
        ('< /summary >', '</summary>'),
        ('< dialog', '<dialog'),
        ('< /dialog >', '</dialog>'),
        ('< menu', '<menu'),
        ('< /menu >', '</menu>'),
        ('< menuitem', '<menuitem'),
        ('< /menuitem >', '</menuitem>'),
        ('< command', '<command'),
        ('< /command >', '</command>'),
        ('< keygen', '<keygen'),
        ('< /keygen >', '</keygen>'),
        ('< output', '<output'),
        ('< /output >', '</output>'),
        ('< progress', '<progress'),
        ('< /progress >', '</progress>'),
        ('< meter', '<meter'),
        ('< /meter >', '</meter>'),
        ('< time', '<time'),
        ('< /time >', '</time>'),
        ('< ruby', '<ruby'),
        ('< /ruby >', '</ruby>'),
        ('< rt', '<rt'),
        ('< /rt >', '</rt>'),
        ('< rp', '<rp'),
        ('< /rp >', '</rp>'),
        ('< bdi', '<bdi'),
        ('< /bdi >', '</bdi>'),
        ('< bdo', '<bdo'),
        ('< /bdo >', '</bdo>'),
        ('< wbr', '<wbr'),
        ('< /wbr >', '</wbr>'),
        ('< datalist', '<datalist'),
        ('< /datalist >', '</datalist>'),
        ('< optgroup', '<optgroup'),
        ('< /optgroup >', '</optgroup>'),
        ('< fieldset', '<fieldset'),
        ('< /fieldset >', '</fieldset>'),
        ('< legend', '<legend'),
        ('< /legend >', '</legend>'),
        ('< colgroup', '<colgroup'),
        ('< /colgroup >', '</colgroup>'),
        ('< col', '<col'),
        ('< /col >', '</col>'),
        ('< caption', '<caption'),
        ('< /caption >', '</caption>'),
        ('< thead', '<thead'),
        ('< /thead >', '</thead>'),
        ('< tbody', '<tbody'),
        ('< /tbody >', '</tbody>'),
        ('< tfoot', '<tfoot'),
        ('< /tfoot >', '</tfoot>'),
        ('< dd', '<dd'),
        ('< /dd >', '</dd>'),
        ('< dt', '<dt'),
        ('< /dt >', '</dt>'),
        ('< dl', '<dl'),
        ('< /dl >', '</dl>'),
        ('< figure', '<figure'),
        ('< /figure >', '</figure>'),
        ('< figcaption', '<figcaption'),
        ('< /figcaption >', '</figcaption>'),
        ('< address', '<address'),
        ('< /address >', '</address>'),
        ('< hgroup', '<hgroup'),
        ('< /hgroup >', '</hgroup>'),
        ('< mark', '<mark'),
        ('< /mark >', '</mark>'),
        ('< small', '<small'),
        ('< /small >', '</small>'),
        ('< del', '<del'),
        ('< /del >', '</del>'),
        ('< ins', '<ins'),
        ('< /ins >', '</ins>'),
        ('< sub', '<sub'),
        ('< /sub >', '</sub>'),
        ('< sup', '<sup'),
        ('< /sup >', '</sup>'),
        ('< i', '<i'),
        ('< /i >', '</i>'),
        ('< b', '<b'),
        ('< /b >', '</b>'),
        ('< u', '<u'),
        ('< /u >', '</u>'),
        ('< s', '<s'),
        ('< /s >', '</s>'),
        ('< strong', '<strong'),
        ('< /strong >', '</strong>'),
        ('< em', '<em'),
        ('< /em >', '</em>'),
        ('< dfn', '<dfn'),
        ('< /dfn >', '</dfn>'),
        ('< code', '<code'),
        ('< /code >', '</code>'),
        ('< samp', '<samp'),
        ('< /samp >', '</samp>'),
        ('< kbd', '<kbd'),
        ('< /kbd >', '</kbd>'),
        ('< var', '<var'),
        ('< /var >', '</var>'),
        ('< cite', '<cite'),
        ('< /cite >', '</cite>'),
        ('< abbr', '<abbr'),
        ('< /abbr >', '</abbr>'),
        ('< q', '<q'),
        ('< /q >', '</q>'),
        ('< blockquote', '<blockquote'),
        ('< /blockquote >', '</blockquote>'),
        ('< pre', '<pre'),
        ('< /pre >', '</pre>'),
        ('< />', '/>'),
        ('> </script>', '></script>'),
        ('> </style>', '></style>'),
        ('# ddd', '#ddd'),
        ('# 333', '#333'),
        ('# 007bff', '#007bff'),
        ('# fff', '#fff'),
        ('# 28a745', '#28a745'),
        ('# dc3545', '#dc3545'),
        ('# ffc107', '#ffc107'),
        ('# 6c757d', '#6c757d'),
        ('# 17a2b8', '#17a2b8'),
        ('# f8f9fa', '#f8f9fa'),
        ('# e9ecef', '#e9ecef'),
        ('# dee2e6', '#dee2e6'),
        ('# ced4da', '#ced4da'),
        ('# adb5bd', '#adb5bd'),
        ('# 6c757d', '#6c757d'),
        ('# 495057', '#495057'),
        ('# 343a40', '#343a40'),
        ('# 212529', '#212529'),
        ('# 000', '#000'),
        ('# f00', '#f00'),
        ('# 0f0', '#0f0'),
        ('# 00f', '#00f'),
        ('# ff0', '#ff0'),
        ('# f0f', '#f0f'),
        ('# 0ff', '#0ff'),
        ('# 800', '#800'),
        ('# 080', '#080'),
        ('# 008', '#008'),
        ('# 880', '#880'),
        ('# 808', '#808'),
        ('# 088', '#088'),
        ('# 444', '#444'),
        ('# 666', '#666'),
        ('# 888', '#888'),
        ('# aaa', '#aaa'),
        ('# ccc', '#ccc'),
        ('# eee', '#eee'),
    ]

    # Aplica as correções
    for broken, fixed in html_fixes:
        codigo = codigo.replace(broken, fixed)

    # Salva o arquivo corrigido
    with open("mostro _unificado_copia_do_v2.py", 'w', encoding='utf-8') as f:
        f.write(codigo)

    print("HTML corrigido com sucesso!")

if __name__ == "__main__":
    corrigir_html()
